from Hypothesis import Hypothesis
from Evidence import Evidence
from Prob import Prob

if __name__ == '__main__':
    h4 = Hypothesis("Demolisher SAM的射程范围为850km。")
    h5 = Hypothesis("6月24日测试的SAM射程时680km。")
    e1 = Evidence("Demolisher SAM的最大射程为850km，可以摧毁在1300米到10000米之间高空飞行的目标。M国对SAM规格的可靠性有90%的信心",'VL','C')
    e2 = Evidence("2017年6月24日，与M国接壤的J国的导弹跟踪雷达站检测到从Tantrum发射的SAM，该地空导弹飞行了大约680公里，并摧毁了飞行在1000米处的目标飞机。",'AC','C')
    print("证据1的推断力为：",end=' ')
    print(e1.getInferentialForce())
    print("证据2的推断力为：",end=' ')
    print(e2.getInferentialForce())
    h4.addFavoringEvidence(e1)
    h5.addFavoringEvidence(e2)
    # h4.test()
    # h5.test()
    print("假设4成立的概率为：",end='')
    print(h4.reason())
    print("假设5成立的概率为：",end='')
    print(h5.reason())

    h2 = Hypothesis("2017年6月24日测试的SAM射程在Demolisher SAM的射程范围内",False,'AND',Prob.C)
    h2.addSubFavoringHypothesis(h4)
    h2.addSubFavoringHypothesis(h5)
    print("假设2成立的概率为：", end="")
    print(h2.reason())

    h6 = Hypothesis("2017年6月24检测到的SAM的射程高度为1000米")
    h7 = Hypothesis("DemolisherSAM的射程高度在1300米和10000米之间")
    h6.addFavoringEvidence(e1)
    h7.addFavoringEvidence(e2)
    print("假设6成立的概率为：",end='')
    print(h6.reason()) # 这个地方一开始没推理，导致h3出错了。应该还是涉及到self._likehood的修改
    print("假设7成立的概率为：",end='')
    print(h7.reason())
    h3 = Hypothesis("J国的导弹跟踪雷达站检测到从Tantrum发射的SAM的射程高度与DemolisherSAM的射程高度不一致",False,'AND',Prob.C)
    h3.addSubFavoringHypothesis(h6)
    h3.addSubFavoringHypothesis(h7)
    print("假设3成立的概率为：",end="")
    print(h3.reason())
    h1 = Hypothesis("M国向Z国出售Demolisher SAM",False,'AND',Prob.C)
    h1.addSubFavoringHypothesis(h2)
    h1.addSubDisfavoringHypothesis(h3)
    print("假设1成立的概率为：",end="")
    print(h1.reason())